language: objective-c
osx_image: xcode7
env:
  - DESTINATION="OS=9.0,name=iPhone 6" SCHEME="SwiftFilter" SDK=iphonesimulator9.0
before_install:
  - gem install xcpretty --no-rdoc --no-ri --no-document --quiet
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -project SwiftFilter.xcodeproj -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
    -configuration Debug ONLY_ACTIVE_ARCH=NO test | xcpretty -c
after_success:
  - bash <(curl -s https://codecov.io/bash)
