language: objective-c
osx_image: xcode7.2
env:
  - DESTINATION="OS=9.0,name=iPhone 6" SCHEME="SwiftFilter" SDK=iphonesimulator
script:
  - xctool -project SwiftFilter.xcodeproj -scheme $SCHEME build test -sdk $SDK GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
